name: Pre-Commit
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      discussions: write
      pull-requests: write
      id-token: write
    steps:
    - name: Pre-Commit
      uses: dasmeta/reusable-actions-workflows/pre-commit@4.2.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        path: modules/
